NXE-175 - filtering based on multiple skills in same about field
mostafa-221/jobcrawler-backend pull request #57
Opened 2020-07-22 07:51 UTC by narayan190290

@mostafa-221 can you please have a review for this PR.

2020-07-27 14:00 UTC, adriaanbakker-java requested changes
Please add some comment as to what this query accomplishes

2020-07-27 14:04 UTC, adriaanbakker-java commented on src/main/java/nl/ordina/jobcrawler/repo/VacancyRepository.java
> +    @Query(value = "SELECT DISTINCT v.* FROM Vacancy AS v " +
please add some comment to the queries to explain what they should deliver

2020-07-28 07:49 UTC, tkoen93 approved these changes

2020-07-28 07:52 UTC, adriaanbakker-java approved these changes

2020-07-28 08:21 UTC, merged